name=input("enter your name")
branch=input("enter your branch")
gender=input("enter your gender")
college=input("enter your college")
age=int(input("enter your age"))
print("your name is ", name)
print("your branch is ", branch)
print("yoyr gender is ",gender)
print("your college is ",college)
print("your age is ",age)
